### ISSUE TITLE
Release petition

### ISSUE THREAD

**Issue by magiblot** [Aktanusa/AreaResize#1]
Could you please compile and release a new version with the AviSynth+ headers update?

Thanks!

**Comment by Aktanusa** [comment]
Sure, should be simple to do.  I was hoping to release it with a rewrite that hopefully also increases performance, but of well.  I'll do it tonight.

**Comment by Aktanusa** [comment]
Done, closing this.

**Comment by magiblot** [comment]
Thank you very much.

**Comment by Aktanusa** [comment]
No problem!
